a = input()
b = input()
c = input()
l = a.split()
l1 = b.split()
l2 = c.split()
s1 = set(l)
s2 = set(l1)
s3 = set(l2)
dif = s1.difference(s2, s3)
print(*dif)
dif1 = s2.difference(s1, s3)
print(*dif1)
dif2 = s3.difference(s2, s1)
print(*dif2)